# Generated by Django 5.0.2 on 2024-02-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
